version : '3'
services:
    php:
        image: intranet:latest
        ports:
        - "7000:80"
        networks:
            vpc:
                ipv4_address: 172.28.1.1
        volumes:
        - ./html:/var/www/html
        links: 
        - mysql
        extra_hosts:
        - "db.trator.w2o:172.28.1.3"
    phpmyadmin:
        image: phpmyadmin:latest
        ports:
        - "8080:80"
        networks:
            vpc:
                ipv4_address: 172.28.1.2
        links: 
        - mysql
        environment:
        - PMA_ARBITRARY=1
    mysql:
        image: mysql:5.7
        command: mysqld --lower_case_table_names=1
        command: mysqld --sql_mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
        ports: 
        - 3306:3306
        networks:
            vpc:
                ipv4_address: 172.28.1.3
        volumes:    
        - ./../mysql:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=root
        extra_hosts:
        - "db.trator.w2o:172.28.1.3"
networks:
    vpc:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16





